---
title: "Market analysis case Red"
number-sections: true
---

You are a marketer working for Red, a company that sells orange juice online. In order to develop a new online marketing strategy you first need to analyze and interpret some essential market figures like market penetration and market share. You’re two top competitors are the companies “Blue” and “Yellow”. 

::: {.callout-note}
Take a look at @sec-glossary to get information about the definition of key market figures.
:::

Solve the following tasks by using 

a) cell formulas in spreadsheets (use Excel or Google Sheets) 
b) Python 



::: {.callout-note}
Take a look at [the slides](/slide.qmd) to get information about the definition of key market figures.
:::

::: {.callout-tip}
## Data

Download the [data](https://docs.google.com/spreadsheets/d/1MlwDNgvhwJoQoh1_-HZsjKK5PW0ZdeQMKQ5GuQGP-94/edit?usp=sharing) as Excel spreadsheet or work directly in Google Sheets.
:::




---

## Market penetration

First, use the market penetration formula (calculates the percentage of customers in the potential market who are currently purchasing a product or service) to determine the growth opportunity for orange juice. 

In this example, Red’s defined current customers as individuals who buy orange juice. This is a subset of the larger group of potential customers (the set of customers who have some interest in a product or service, or to whom the product is potentially relevant)— individuals who buy a variety of other juices. 

Calculate both the (1) market penetration and the (2) market growth opportunity.

## Market penetration by segment

Next, identify market segments and use the market penetration formula to determine the growth potential for each of the segments.

Red identified three customer segments of the 150 million juice consumers based on the number of bottles an individual purchased per year: 

- frequent buyers
- moderate buyers 
- occasional buyers 

These market segments are a subset of the total current or potential customers in the market. They add up to the total number of customers. 

The market penetration formula helps you determine the growth potential for each of these three market segments.

## Potential market sales

Next, estimate annual sales (in (1) units and (2) gross revenue) for each segment of the juice market. Then add up the segment results to find the total potential sales. 

On average, *frequent buyers* purchased 21 bottles of juice last year and were very price-sensitive. They waited for sales or used coupons so that they paid only $1.99 for a bottle of juice. 

*Moderate buyers* purchased eight bottles of juice, sometimes on sale, but sometimes at full price, so they paid, on average, $3.49 for a bottle of juice. 

*Occasional buyers* purchased three bottles of juice and were price-insensitive, usually paying full price, $4.99, for a bottle of juice.

## Current market sales

Now find the current market sales (in units and revenue) for orange juice by segment. Then add up the segment results to find the total current sales.

## Current market share by segment

Next, calculate the market share of each segment of the current orange juice market in terms of customers, bottles, and revenue.

Divide each market segment’s quantity by the total amount (the sum of all three segments) of customers, bottles, and revenue.

## Current market units and average price

Use the current market’s total sales, in units and revenue, to determine, on average, how many bottles of orange juice each customer purchases and at what price. 

Later, you will use these averages to help you analyze pricing and individual customer sales across all orange juice brands.


## Current market average units/price by brand

Now you’re ready to calculate the average number of bottles purchased by a customer of Red, Blue, and Yellow (use dataset-2). 

Divide each brand’s bottles by its total customers. Then calculate the average price paid for a Red, Blue, and Yellow bottle by dividing the total revenue by the total bottles. Compare these results with the general averages that you calculated in  6.

## Current market share by brand

Now analyze the competition. Compare Red with its top two competitors, Blue and Yellow. Analyze the market share of each brand in terms of customers, units, and revenue (use dataset-2).


## Glossary {#sec-glossary}

**Current market**: The total number of customers, units, or revenue currently being generated in the market.

**Market penetration formula:** Calculates the percentage of customers in the potential market who are currently purchasing a product or service.

**Market segment:** A subset of the total current or potential customers in a market.

**Market share**: The percentage of the total demand that a company has captured in terms of units sold or gross revenue.

**Potential market:** The set of customers who have some interest in a product or service, or to whom the product is potentially relevant.
